#!/bin/sh
# Migration 10 --> 11

# Force reconcile hr keycloak-configure
if kubectl get helmrelease keycloak-configure -n quantum-keycloak; then
  kubectl delete po -l app=source-controller -n quantum-fluxcd
  timestamp=$(date --rfc-3339=ns)
  kubectl annotate helmrelease keycloak-configure -n quantum-keycloak \
    reconcile.fluxcd.io/forceAt="$timestamp" \
    reconcile.fluxcd.io/requestedAt="$timestamp" \
    --overwrite
fi

# Write version to quantumreasoning-version config
kubectl create configmap -n quantum-system quantumreasoning-version --from-literal=version=11 --dry-run=client -o yaml | kubectl apply -f-
