#!/bin/sh
# Migration 3 --> 4

# Fix kubeovn crds
kubeovn_crds=$(kubectl get crd -o name | grep '\.kubeovn\.io$')
if [ -n "$kubeovn_crds" ]; then
  kubectl annotate $kubeovn_crds meta.helm.sh/release-namespace=quantum-kubeovn meta.helm.sh/release-name=kubeovn
  kubectl label $kubeovn_crds app.kubernetes.io/managed-by=Helm
fi

# Write version to quantumreasoning-version config
kubectl create configmap -n quantum-system quantumreasoning-version --from-literal=version=4 --dry-run=client -o yaml | kubectl apply -f-
