flux-operator:
  fullnameOverride: flux-operator
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoSchedule
  hostNetwork: true
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi
