cilium:
  kubeProxyReplacement: true
  hostFirewall:
    enabled: true
  hubble:
    enabled: false
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  loadBalancer:
    algorithm: maglev
  ipam:
    mode: "kubernetes"
  image:
    repository: ghcr.io/quantumreasoning/quantumreasoning/cilium
    tag: 1.17.5
    digest: "sha256:afd0432bcd733c60cc4521bdfa6d12538ae52f6b4410a0d2bd062ea42732bd53"
  envoy:
    enabled: false
