{{- $quantumConfig := lookup "v1" "ConfigMap" "quantum-system" "quantumreasoning" }}
{{- $oidcEnabled := index $quantumConfig.data "oidc-enabled" }}
{{- if $oidcEnabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: info
  namespace: {{ include "tenant.name" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    quantumreasoning.io/ui: "true"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  chart:
    spec:
      chart: info
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: quantumreasoning-extra
        namespace: quantum-public
      version: "*"
  interval: 1m0s
  timeout: 5m0s
{{- end }}
