apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-csi
  labels:
    quantumreasoning.io/repository: system
    quantumreasoning.io/target-cluster-name: {{ .Release.Name }}
spec:
  interval: 5m
  releaseName: csi
  chart:
    spec:
      chart: quantum-kubevirt-csi-node
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: quantumreasoning-system
        namespace: quantum-system
      version: '>= 0.0.0-0'
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: quantum-csi
  storageNamespace: quantum-csi
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- with .Values.storageClass }}
  values:
    storageClass: "{{ . }}"
  {{- end }}
  dependsOn:
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
