apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-system
spec:
  chart:
    spec:
      chart: quantum-bucket
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: quantumreasoning-system
        namespace: quantum-system
      version: '>= 0.0.0-0'
  interval: 1m0s
  timeout: 5m0s
  values:
    bucketName: {{ .Release.Name }}
