{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quantum-proxy.fullname" . }}
  labels:
    {{- include "quantum-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quantum-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "quantum-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
