{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quantum-proxy.fullname" . }}
  labels:
    {{- include "quantum-proxy.labels" . | nindent 4 }}
{{- end }}
