kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v42.8.1@sha256:675938648e40ae66ad4439e9ea6f0559e137a2e1fe5f3f0f98ac50a0531d8b0d
    repository: ghcr.io/quantumreasoning/quantumreasoning/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
