apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.apps.quantumreasoning.io
spec:
  insecureSkipTLSVerify: true
  group: apps.quantumreasoning.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: quantumreasoning-api
    namespace: quantum-system
  version: v1alpha1
