apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quantumreasoning-api-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: quantumreasoning-api
  namespace: quantum-system
