apiVersion: v1
kind: ConfigMap
metadata:
  name: quantumreasoning-api
  namespace: quantum-system
data:
  config.yaml: |
    resources:
    - application:
        kind: Bucket
        singular: bucket
        plural: buckets
      release:
        prefix: bucket-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: bucket
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: ClickHouse
        singular: clickhouse
        plural: clickhouses
      release:
        prefix: clickhouse-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: clickhouse
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: HTTPCache
        singular: httpcache
        plural: httpcaches
      release:
        prefix: http-cache-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: http-cache
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: NATS
        singular: nats
        plural: natses
      release:
        prefix: nats-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: nats
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: TCPBalancer
        singular: tcpbalancer
        plural: tcpbalancers
      release:
        prefix: tcp-balancer-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: tcp-balancer
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: VirtualMachine
        singular: virtualmachine
        plural: virtualmachines
      release:
        prefix: virtual-machine-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: virtual-machine
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: VPN
        singular: vpn
        plural: vpns
      release:
        prefix: vpn-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: vpn
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: MySQL
        singular: mysql
        plural: mysqls
      release:
        prefix: mysql-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: mysql
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Tenant
        singular: tenant
        plural: tenants
      release:
        prefix: tenant-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: tenant
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Kubernetes
        singular: kubernetes
        plural: kuberneteses
      release:
        prefix: kubernetes-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: kubernetes
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Redis
        singular: redis
        plural: redises
      release:
        prefix: redis-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: redis
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: RabbitMQ
        singular: rabbitmq
        plural: rabbitmqs
      release:
        prefix: rabbitmq-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: rabbitmq
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Postgres
        singular: postgres
        plural: postgreses
      release:
        prefix: postgres-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: postgres
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: FerretDB
        singular: ferretdb
        plural: ferretdb
      release:
        prefix: ferretdb-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: ferretdb
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Kafka
        singular: kafka
        plural: kafkas
      release:
        prefix: kafka-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: kafka
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: VMDisk
        plural: vmdisks
        singular: vmdisk
      release:
        prefix: vm-disk-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: vm-disk
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: VMInstance
        plural: vminstances
        singular: vminstance
      release:
        prefix: vm-instance-
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: vm-instance
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-apps
            namespace: quantum-public
    - application:
        kind: Monitoring
        plural: monitorings
        singular: monitoring
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: monitoring
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
    - application:
        kind: Etcd
        plural: etcds
        singular: etcd
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: etcd
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
    - application:
        kind: Ingress
        plural: ingresses
        singular: ingress
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: ingress
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
    - application:
        kind: SeaweedFS
        plural: seaweedfses
        singular: seaweedfs
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: seaweedfs
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
    - application:
        kind: BootBox
        plural: bootboxes
        singular: bootbox
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: bootbox
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
    - application:
        kind: Info
        plural: infos
        singular: info
      release:
        prefix: ""
        labels:
          quantumreasoning.io/ui: "true"
        chart:
          name: info
          sourceRef:
            kind: HelmRepository
            name: quantumreasoning-extra
            namespace: quantum-public
