apiVersion: v1
kind: Service
metadata:
  name: quantumreasoning-api
  namespace: quantum-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: quantumreasoning-api
