---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: quantumreasoning-system
  namespace: quantum-system
  labels:
    quantumreasoning.io/repository: system
spec:
  interval: 5m0s
  url: http://quantumreasoning.quantum-system.svc/repos/system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: quantumreasoning-apps
  namespace: quantum-public
  labels:
    quantumreasoning.io/ui: "true"
    quantumreasoning.io/repository: apps
spec:
  interval: 5m0s
  url: http://quantumreasoning.quantum-system.svc/repos/apps
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: quantumreasoning-extra
  namespace: quantum-public
  labels:
    quantumreasoning.io/repository: extra
spec:
  interval: 5m0s
  url: http://quantumreasoning.quantum-system.svc/repos/extra
